export default {
  //labels
  save: 'Save',
  update: 'Update',
  reset: 'Reset',
  name: 'Name',
  isActive: 'Is Active?',
  isAnActiveCategory: 'Is An Active Category?',
  en: 'en',
  es: 'es',
  cr: 'cr',
  contactName: 'Contact Name',
  contactEmail: 'Contact Email',
  contactPhone: 'Contact Phone',
  address: 'Address',
  city: 'City',
  region: 'Region',
  country: 'Country',
  unitPrice: 'Unit Price',
  quantityPerUnit: 'Quantity Per Unit',
  unitStock: 'Unit Stock',
  orderLevel: 'Order Level',
  isDiscontinued: 'Is Discontinued?',
  picture: 'Picture',
  createdDate: 'Created Date',
  createdBy: 'Created By',
  modifiedDate: 'Modified Date',
  modifiedBy: 'Modified By',

  //navbars
  home: 'Home',
  list: 'List',
  create: 'Create',
  category: 'Category',
  listCategory: 'List Categories',
  createCategory: 'Create a Category',
  editCategory: 'Edit Category',
  supplier: 'Supplier',
  listSupplier: 'List Suppliers',
  createSupplier: 'Create a Supplier',
  editSupplier: 'Edit Supplier',
  product: 'Product',
  listProduct: 'List Products',
  createProduct: 'Create a Product',
  editProduct: 'Edit Product',
  language: 'Language',
  english: 'English',
  spanish: 'Spanish',
  creole: 'Creole',

  //validations
  emptyField: 'This field is required',
  emailField: 'This field must be an email',
  lengthField: 'This field must have a length of: ',
  characters: 'Characters',
  invalidFormat: 'This field has an invalid format',

  //validation messages
  message: 'Message',
  error: 'Error',
  successfullySaved: 'Successfully Saved',
  actionText: 'Actions',
  editText: 'Edit',
  deleteText: 'Delete',
  detailText: 'Details',
  areYouSure: 'Are You Sure?',
  warningDelete: 'You will not be able to recover this information',
  keepIt: 'No, keep it',
  deleteIt: 'Yes, delete it',
  deleted: 'Delete',
  deletedSuccess: 'The information was delete successfully',
  cancelled: 'Cancelled',
  deleteCancelled: 'Your information is safe',
  noData: 'We did not find any data to be displayed'
};
