export default {
  //labels
  save: 'Guardar',
  update: 'Actualizar',
  reset: 'Limpiar',
  name: 'Nombre',
  isActive: 'Esta Activo(a)?',
  isAnActiveCategory: 'Es una categoria activa?',
  en: 'en',
  es: 'es',
  cr: 'cr',
  contactName: 'Nombre del Contacto',
  contactEmail: 'Email del Contacto',
  contactPhone: 'Telefono del Contacto',
  address: 'Direccion',
  city: 'Ciudad',
  region: 'Region',
  country: 'Pais',
  unitPrice: 'Precio Unitario',
  quantityPerUnit: 'Cantidad Por Unidad',
  unitStock: 'Unidad de Stock',
  orderLevel: 'Nivel de la Orden',
  isDiscontinued: 'Esta Suspendido?',
  picture: 'Imagen',
  createdDate: 'Fecha De Creacion',
  createdBy: 'Creado Por',
  modifiedDate: 'Fecha de modificacion',
  modifiedBy: 'Modificado Por',

  //navbars
  home: 'Inicio',
  list: 'Listar',
  create: 'Crear',
  category: 'Categoria',
  listCategory: 'Listar Categorias',
  createCategory: 'Crear Categoria',
  editCategory: 'Editar Categoria',
  supplier: 'Suplidor',
  listSupplier: 'Listar Suplidores',
  createSupplier: 'Crear Suplidor',
  editSupplier: 'Editar Suplidor',
  product: 'Producto',
  listProduct: 'Listar Productos',
  createProduct: 'Crear Producto',
  editProduct: 'Editar Producto',
  language: 'Idioma',
  english: 'Ingles',
  spanish: 'Español',
  creole: 'Creole',

  //validations
  emptyField: 'Este campo es requerido',
  emailField: 'Este campo debe ser un email',
  lengthField: 'Este campo debe tener un largo de: ',
  characters: 'Caracteres',
  invalidFormat: 'Este campo tiene un formato invalido',
  message: 'Mensaje',
  error: 'Error',
  successfullySaved: 'Guardado con exito',
  actionText: 'Acciones',
  editText: 'Editar',
  deleteText: 'Eliminar',
  detailText: 'Detalles',
  areYouSure: 'Estas Seguro?',
  warningDelete: 'No podras recuperar esta informacion',
  keepIt: 'No, conservalo',
  deleteIt: 'Si, eliminalo',
  deleted: 'Eliminado',
  deletedSuccess: 'La informacion fue eliminada con exito',
  cancelled: 'Cancelado',
  deleteCancelled: 'Tu informacion esta segura',
  noData: 'No se encontro datos para ser mostrado'
};
